name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install all dependencies
    - name: Install dependencies
      run: npm ci

    # Install necessary Playwright dependencies
    - name: Install Playwright dependencies
      run: npx playwright install-deps

    # Install ts-node (for TypeScript)
    - name: Install ts-node
      run: npm i ts-node -D

    # Ensure the reports directory exists
    - name: Create reports directory
      run: mkdir -p reports

    # Run the tests using cucumber
    - name: Run Cucumber Tests
      run: npm test

    # Upload test report artifacts
    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Report
        path: reports
        retention-days: 2

    # Build the project (optional, only if your project has a build step)
    - name: Build project
      run: npm run build --if-present
